# -*- coding: utf-8 -*-
"""sistemaexperto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19D1e1SH6cbUKDeD5H7rfBEMBIx0EdqmL
"""



def sistema_experto_basico():
  pause = int(input("Desea utilizar el sistema experto? SI = 0 NO = 1"))
  sintomas_gripa = ["friebre","tos","malestar"]
  sintomas_faringitis = ["dolor_garganta","malestar"]
  faringitis=0
  gripa=0
  while(pause == 0):
    a = input("Que sintoma tiene?")
    if(a in sintomas_gripa and a in sintomas_faringitis):
      gripa +=1
      faringitis +=1 
    elif(a in sintomas_faringitis):
      faringitis +=1
    elif(a in sintomas_gripa):
      gripa +=1
    else:
      print("no escribio ninguno de los sintomas permitidos")
    pause = int(input("Desea utilizar de nuevo el sistema experto? SI = 0 NO = 1")) 

  if(gripa > faringitis):
    print("tiene gripa")
  elif(faringitis > gripa):
    print("tiene faringitis")  
  else:
    print("no se puede identificar el sintoma")

sistema_experto_basico()